AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  google-exporter
  
Globals:
  Function:
    Timeout: 3

Parameters:
  GoogleOAuthClientId:
      Type: String
      Description: "Google OAuth ClientId"
  GoogleOauthSecret:      
      Type: String
      Description: "Google OAuth Secret"
     # NoEcho: true      
  RecipeId:
      Type: String
      Description: "Alloy Recipe Id:"
  
Resources:
  GoogleOAuthSecret:
    Type: AWS::SecretsManager::Secret
    Properties: 
      Description: Secrets for connecting to  Google OAuth Service
      Name: /google/oauth
      SecretString: !Sub '{"client_id": "${GoogleOAuthClientId}", "client_secret": "${GoogleOauthSecret}"}' 
  GoogleExporterAPI:
    Type: AWS::Serverless::HttpApi    
  RequestAuthenticationFunction:
    Type: AWS::Serverless::Function 
    Properties:
      CodeUri: dist/
      Handler: app.requestAuth
      Runtime: nodejs12.x              
      Policies:
        AWSSecretsManagerGetSecretValuePolicy:
          SecretArn: !Ref GoogleOAuthSecret
      Events:
        RequestAuthentication:
          Type: HttpApi 
          Properties:
            ApiId: !Ref GoogleExporterAPI
            Path: /request-authentication
            Method: GET
  RedirectToAppFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: dist/
      Handler: app.redirectToApp
      Runtime: nodejs12.x
      Environment: 
        Variables:
          alloyKey: !Ref GoogleExporterAlloyKey
          recipeId: !Ref RecipeId
      Policies:
        - AWSSecretsManagerGetSecretValuePolicy:
            SecretArn: !Ref GoogleOAuthSecret
        - DynamoDBWritePolicy:
            TableName: GoogleExporterOAuthTable
        - Statement:
            - Sid: EnableLambdaSignKMS
              Effect: Allow
              Action: kms:Sign
              Resource: !Sub 'arn:${AWS::Partition}:kms:${AWS::Region}:${AWS::AccountId}:key/${GoogleExporterAlloyKey}'
              
      Events:
          RedirectToApp:
            Type: HttpApi
            Properties:
              ApiId: !Ref GoogleExporterAPI
              Path: /redirect-to-app
              Method: GET
  AlloyCardWebhookFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: dist/
      Handler: app.alloyWebhook
      Runtime: nodejs12.x
      Events:
        AlloyWebhook:
          Type: HttpApi
          Properties:
            ApiId: !Ref GoogleExporterAPI
            Path: /alloy-webhook
            Method: POST

  GoogleExporterAlloyKey: 
    Type: AWS::KMS::Key
    Properties: 
      Description: Key to Access AlloyCard resources
      Enabled: true
      EnableKeyRotation: false
      KeyPolicy:
        Version: '2012-10-17'
        Id: key-allow-root
        Statement:
        - Sid: Enable IAM User Permissions
          Effect: Allow
          Principal: 
            AWS:  !Sub 'arn:aws:iam::${AWS::AccountId}:root'
          Action: kms:*
          Resource: '*'
      KeySpec: RSA_2048
      KeyUsage: SIGN_VERIFY
      PendingWindowInDays: 7
  AccessTokenTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      TableName: GoogleExporterOAuthTable

Outputs:
  RequestAuthenticationFunctionApi:
    Description: "API Gateway endpoint URL for Prod stage for GoogleExporter function"
    Value: !Sub "https://${GoogleExporterAPI}.execute-api.${AWS::Region}.amazonaws.com/request-authentication"
  RequestAuthenticationFunction:
    Description: "GoogleExporter Lambda Function ARN"
    Value: !GetAtt RequestAuthenticationFunction.Arn
  RequestAuthenticationFunctionIamRole:
    Description: "Implicit IAM Role created for GoogleExporter function"
    Value: !GetAtt RequestAuthenticationFunctionRole.Arn
  AlloyKey:
    Description: "Alloy Public Recipe Key"
    Value: !Ref GoogleExporterAlloyKey
